### ISSUE TITLE
How to use with blaze

### ISSUE THREAD

**Issue by JoshuaNovak919** [danielqiu/feed#4]
Sorry if this is a dumb question, but i'm new to Meteor and i'm not sure how I can access the feed in my template. Anyone know how to do this?

**Comment by danielqiu** [comment]
@JoshuaNovak919 ,I could make my client side code open sourced but it might take some time.

**Comment by JoshuaNovak919** [comment]
I actually figured it out, so it's not a problem. Thanks though. Once I ran it in startup and published/subscribed etc I was good to go.
